server:
  port: 8080
spring:
  application:
    name: xjjxmm
  redis:
    host: localhost
    port: 6379

  # datasource
  datasource:
    url: jdbc:mysql://localhost:3306/estimate?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus
mybatis-plus:
  #  检查XML映射文件
  # check-config-location: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #global-config:
    #db-config:
      #table-prefix: ms_
  mapper-locations: classpath*:mapper/*Mapper.xml


#log
logging:
  level:
    com.xjjxmm.estimate: debug


# token 加密密钥
# token 过期时间，以秒为单位，604800 是 一星期

token:
  secret: secret
  expiration: 604800
  header: X_Auth_Token





